# Generated by Django 4.1.4 on 2022-12-31 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0002_alter_departamento_short_name'),
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='lasst_name',
            new_name='last_name',
        ),
        migrations.AddField(
            model_name='empleado',
            name='departamento',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='departamento.departamento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empleado',
            name='job',
            field=models.CharField(choices=[('0', 'Contador'), ('1', 'Administrador'), ('2', 'Economista'), ('3', 'Otro')], default='3', max_length=50, verbose_name='Trabajo'),
        ),
    ]
